version: '3'
services:
  webserver1:
    image: httpd:latest
    container_name: apache_web1
    volumes:
      - ./website1:/usr/local/apache2/htdocs/
    networks:
      - webnet
    ports:
      - "8081:80"

  webserver2:
    image: httpd:latest
    container_name: apache_web2
    volumes:
      - ./website2:/usr/local/apache2/htdocs/
    networks:
      - webnet
    ports:
      - "8082:80"

  nginx:
    image: nginx:latest
    container_name: nginx_loadbalancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - webserver1
      - webserver2
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
